version: '3'
services:
  web:
    build: ./flask
    volumes:
      - ./flask:/usr/src/flask
    ports:
      - 5000:5000
    depends_on:
      - database
  
  database:
    image: postgres:13.1
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres    

volumes:
  database-data: 
